### ISSUE TITLE
Modificare tipo di mappa

### ISSUE THREAD

**Issue by Pinzauti** [Pinzauti/Segnalazioni-Terremoto#1]
Sostituire mappa Gmaps in una mappa con formato compatibile.

**Comment by iltempe** [comment]
In particolare se vogliamo rendere dati aperti va fatto con base Openstreetmap.

**Comment by iltempe** [comment]
ad esempio http://www.liedman.net/leaflet-control-geocoder/

**Comment by iltempe** [comment]
oppure http://www.d3noob.org/2014/02/searching-leafletjs-map-using.html

**Comment by iltempe** [comment]
oppure appunto http://www.piersoft.it/terremotocentro/mappa.php
